// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-indicators.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_indicators_default = defineTool({
  name: "list_indicators",
  title: "Listar indicadores",
  description: "Lista os indicadores de qualidade cadastrados no Qualitoo do usu\xE1rio autenticado.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await client(ctx).from("indicators").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { indicators: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-nonconformities.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_nonconformities_default = defineTool2({
  name: "list_nonconformities",
  title: "Listar n\xE3o conformidades",
  description: "Lista as n\xE3o conformidades (NCs) do Qualitoo, com filtro opcional por severidade e status.",
  inputSchema: {
    severity: z2.enum(["low", "medium", "high", "critical"]).optional(),
    status: z2.string().optional(),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ severity, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = client2(ctx).from("non_conformities").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (severity) q = q.eq("severity", severity);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { non_conformities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-nonconformity.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_nonconformity_default = defineTool3({
  name: "create_nonconformity",
  title: "Registrar n\xE3o conformidade",
  description: "Registra uma nova n\xE3o conformidade (NC) no Qualitoo em nome do usu\xE1rio autenticado.",
  inputSchema: {
    title: z3.string().min(3).max(200).describe("T\xEDtulo curto da NC."),
    description: z3.string().min(5).describe("Descri\xE7\xE3o detalhada."),
    severity: z3.enum(["low", "medium", "high", "critical"]).describe("Severidade da NC."),
    sector: z3.string().optional().describe("Setor/\xE1rea hospitalar (ex.: UTI, Emerg\xEAncia).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, severity, sector }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await client3(ctx).from("non_conformities").insert({
      title,
      description,
      severity,
      sector: sector ?? null,
      status: "open",
      created_by: ctx.getUserId()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `NC criada: ${data.id}` }],
      structuredContent: { non_conformity: data }
    };
  }
});

// src/lib/mcp/tools/list-action-plans.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_action_plans_default = defineTool4({
  name: "list_action_plans",
  title: "Listar planos de a\xE7\xE3o",
  description: "Lista os planos de a\xE7\xE3o (5W2H) cadastrados no Qualitoo.",
  inputSchema: { limit: z4.number().int().min(1).max(200).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await client4(ctx).from("action_plans").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { action_plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-audits.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_audits_default = defineTool5({
  name: "list_audits",
  title: "Listar auditorias",
  description: "Lista as auditorias cadastradas no Qualitoo.",
  inputSchema: { limit: z5.number().int().min(1).max(200).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await client5(ctx).from("audits").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { audits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-risks.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_risks_default = defineTool6({
  name: "list_risks",
  title: "Listar riscos",
  description: "Lista os riscos cadastrados na matriz de riscos do Qualitoo.",
  inputSchema: { limit: z6.number().int().min(1).max(200).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await client6(ctx).from("risks").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { risks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool7({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado no Qualitoo (id, email, cliente OAuth).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yedvaofwlaaydewnowuq";
var mcp_default = defineMcp({
  name: "qualitoo-mcp",
  title: "Qualitoo",
  version: "0.1.0",
  instructions: "Ferramentas do Qualitoo \u2014 Sistema de Gest\xE3o da Qualidade Hospitalar. Use as tools de leitura para consultar indicadores, n\xE3o conformidades, planos de a\xE7\xE3o, auditorias e riscos do usu\xE1rio autenticado. Use `create_nonconformity` para registrar uma nova NC. Todas as chamadas respeitam as permiss\xF5es (RLS) do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_indicators_default,
    list_nonconformities_default,
    create_nonconformity_default,
    list_action_plans_default,
    list_audits_default,
    list_risks_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
